<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="15">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>LSTM_Top</name>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>14</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>in_data_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>in.data.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>in_keep_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>in.keep.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_3">
          <Value>
            <Obj>
              <type>1</type>
              <id>3</id>
              <name>in_strb_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>in.strb.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_4">
          <Value>
            <Obj>
              <type>1</type>
              <id>4</id>
              <name>in_user_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>in.user.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_5">
          <Value>
            <Obj>
              <type>1</type>
              <id>5</id>
              <name>in_last_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>in.last.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_6">
          <Value>
            <Obj>
              <type>1</type>
              <id>6</id>
              <name>in_id_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>in.id.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_7">
          <Value>
            <Obj>
              <type>1</type>
              <id>7</id>
              <name>in_dest_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>in.dest.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_8">
          <Value>
            <Obj>
              <type>1</type>
              <id>8</id>
              <name>out_data_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>out.data.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_9">
          <Value>
            <Obj>
              <type>1</type>
              <id>9</id>
              <name>out_keep_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>out.keep.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_10">
          <Value>
            <Obj>
              <type>1</type>
              <id>10</id>
              <name>out_strb_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>out.strb.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>4</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_11">
          <Value>
            <Obj>
              <type>1</type>
              <id>11</id>
              <name>out_user_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>out.user.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_12">
          <Value>
            <Obj>
              <type>1</type>
              <id>12</id>
              <name>out_last_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>out.last.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_13">
          <Value>
            <Obj>
              <type>1</type>
              <id>13</id>
              <name>out_id_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>out.id.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_14">
          <Value>
            <Obj>
              <type>1</type>
              <id>14</id>
              <name>out_dest_V</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>out.dest.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_15">
          <Value>
            <Obj>
              <type>0</type>
              <id>179</id>
              <name>_ln39</name>
              <fileName>LSTM/rnn_top.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>39</lineNumber>
              <contextFuncName>LSTM_Top</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="10" tracking_level="0" version="0">
                  <first>C:\Users\fd_reality\AppData\Roaming\Xilinx\Vivado</first>
                  <second class_id="11" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="12" tracking_level="0" version="0">
                      <first class_id="13" tracking_level="0" version="0">
                        <first>LSTM/rnn_top.cpp</first>
                        <second>LSTM_Top</second>
                      </first>
                      <second>39</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>grp_lipnet_lstm_fu_196</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>88</count>
            <item_version>0</item_version>
            <item>183</item>
            <item>184</item>
            <item>185</item>
            <item>186</item>
            <item>187</item>
            <item>188</item>
            <item>189</item>
            <item>190</item>
            <item>191</item>
            <item>192</item>
            <item>193</item>
            <item>194</item>
            <item>195</item>
            <item>196</item>
            <item>197</item>
            <item>198</item>
            <item>199</item>
            <item>200</item>
            <item>201</item>
            <item>202</item>
            <item>203</item>
            <item>204</item>
            <item>205</item>
            <item>206</item>
            <item>207</item>
            <item>208</item>
            <item>209</item>
            <item>210</item>
            <item>211</item>
            <item>212</item>
            <item>213</item>
            <item>214</item>
            <item>215</item>
            <item>216</item>
            <item>217</item>
            <item>218</item>
            <item>219</item>
            <item>220</item>
            <item>221</item>
            <item>222</item>
            <item>223</item>
            <item>224</item>
            <item>225</item>
            <item>226</item>
            <item>227</item>
            <item>228</item>
            <item>229</item>
            <item>230</item>
            <item>231</item>
            <item>232</item>
            <item>233</item>
            <item>234</item>
            <item>235</item>
            <item>236</item>
            <item>237</item>
            <item>238</item>
            <item>239</item>
            <item>240</item>
            <item>241</item>
            <item>242</item>
            <item>243</item>
            <item>244</item>
            <item>245</item>
            <item>246</item>
            <item>247</item>
            <item>248</item>
            <item>249</item>
            <item>250</item>
            <item>251</item>
            <item>252</item>
            <item>253</item>
            <item>254</item>
            <item>255</item>
            <item>256</item>
            <item>257</item>
            <item>258</item>
            <item>259</item>
            <item>260</item>
            <item>261</item>
            <item>262</item>
            <item>263</item>
            <item>264</item>
            <item>265</item>
            <item>266</item>
            <item>267</item>
            <item>268</item>
            <item>269</item>
            <item>270</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>6.07</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_16">
          <Value>
            <Obj>
              <type>0</type>
              <id>180</id>
              <name>_ln41</name>
              <fileName>LSTM/rnn_top.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>41</lineNumber>
              <contextFuncName>LSTM_Top</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>C:\Users\fd_reality\AppData\Roaming\Xilinx\Vivado</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>LSTM/rnn_top.cpp</first>
                        <second>LSTM_Top</second>
                      </first>
                      <second>41</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_17">
          <Value>
            <Obj>
              <type>2</type>
              <id>182</id>
              <name>lipnet_lstm</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:lipnet_lstm&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_18">
          <Obj>
            <type>3</type>
            <id>181</id>
            <name>LSTM_Top</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>2</count>
            <item_version>0</item_version>
            <item>179</item>
            <item>180</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>88</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_19">
          <id>183</id>
          <edge_type>1</edge_type>
          <source_obj>182</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_20">
          <id>184</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_21">
          <id>185</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_22">
          <id>186</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_23">
          <id>187</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_24">
          <id>188</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>189</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>190</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>191</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>192</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>193</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>194</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>195</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>196</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>197</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>198</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>199</id>
          <edge_type>1</edge_type>
          <source_obj>18</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>200</id>
          <edge_type>1</edge_type>
          <source_obj>20</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>201</id>
          <edge_type>1</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>202</id>
          <edge_type>1</edge_type>
          <source_obj>24</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>203</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>204</id>
          <edge_type>1</edge_type>
          <source_obj>28</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>205</id>
          <edge_type>1</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>206</id>
          <edge_type>1</edge_type>
          <source_obj>32</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>207</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>208</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>209</id>
          <edge_type>1</edge_type>
          <source_obj>38</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>210</id>
          <edge_type>1</edge_type>
          <source_obj>40</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>211</id>
          <edge_type>1</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>212</id>
          <edge_type>1</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>213</id>
          <edge_type>1</edge_type>
          <source_obj>46</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>214</id>
          <edge_type>1</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>215</id>
          <edge_type>1</edge_type>
          <source_obj>50</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>216</id>
          <edge_type>1</edge_type>
          <source_obj>52</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>217</id>
          <edge_type>1</edge_type>
          <source_obj>54</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>218</id>
          <edge_type>1</edge_type>
          <source_obj>56</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>219</id>
          <edge_type>1</edge_type>
          <source_obj>58</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>220</id>
          <edge_type>1</edge_type>
          <source_obj>60</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>221</id>
          <edge_type>1</edge_type>
          <source_obj>62</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>222</id>
          <edge_type>1</edge_type>
          <source_obj>64</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>223</id>
          <edge_type>1</edge_type>
          <source_obj>66</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>224</id>
          <edge_type>1</edge_type>
          <source_obj>68</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>225</id>
          <edge_type>1</edge_type>
          <source_obj>70</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>226</id>
          <edge_type>1</edge_type>
          <source_obj>72</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>227</id>
          <edge_type>1</edge_type>
          <source_obj>74</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>228</id>
          <edge_type>1</edge_type>
          <source_obj>76</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>229</id>
          <edge_type>1</edge_type>
          <source_obj>78</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_66">
          <id>230</id>
          <edge_type>1</edge_type>
          <source_obj>80</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_67">
          <id>231</id>
          <edge_type>1</edge_type>
          <source_obj>82</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_68">
          <id>232</id>
          <edge_type>1</edge_type>
          <source_obj>84</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_69">
          <id>233</id>
          <edge_type>1</edge_type>
          <source_obj>86</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_70">
          <id>234</id>
          <edge_type>1</edge_type>
          <source_obj>88</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_71">
          <id>235</id>
          <edge_type>1</edge_type>
          <source_obj>90</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_72">
          <id>236</id>
          <edge_type>1</edge_type>
          <source_obj>92</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_73">
          <id>237</id>
          <edge_type>1</edge_type>
          <source_obj>94</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_74">
          <id>238</id>
          <edge_type>1</edge_type>
          <source_obj>96</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_75">
          <id>239</id>
          <edge_type>1</edge_type>
          <source_obj>98</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_76">
          <id>240</id>
          <edge_type>1</edge_type>
          <source_obj>100</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_77">
          <id>241</id>
          <edge_type>1</edge_type>
          <source_obj>102</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_78">
          <id>242</id>
          <edge_type>1</edge_type>
          <source_obj>104</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_79">
          <id>243</id>
          <edge_type>1</edge_type>
          <source_obj>106</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_80">
          <id>244</id>
          <edge_type>1</edge_type>
          <source_obj>108</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_81">
          <id>245</id>
          <edge_type>1</edge_type>
          <source_obj>110</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_82">
          <id>246</id>
          <edge_type>1</edge_type>
          <source_obj>112</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_83">
          <id>247</id>
          <edge_type>1</edge_type>
          <source_obj>114</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_84">
          <id>248</id>
          <edge_type>1</edge_type>
          <source_obj>116</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_85">
          <id>249</id>
          <edge_type>1</edge_type>
          <source_obj>118</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_86">
          <id>250</id>
          <edge_type>1</edge_type>
          <source_obj>120</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_87">
          <id>251</id>
          <edge_type>1</edge_type>
          <source_obj>122</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_88">
          <id>252</id>
          <edge_type>1</edge_type>
          <source_obj>124</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_89">
          <id>253</id>
          <edge_type>1</edge_type>
          <source_obj>126</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_90">
          <id>254</id>
          <edge_type>1</edge_type>
          <source_obj>128</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_91">
          <id>255</id>
          <edge_type>1</edge_type>
          <source_obj>130</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_92">
          <id>256</id>
          <edge_type>1</edge_type>
          <source_obj>132</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_93">
          <id>257</id>
          <edge_type>1</edge_type>
          <source_obj>134</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_94">
          <id>258</id>
          <edge_type>1</edge_type>
          <source_obj>136</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_95">
          <id>259</id>
          <edge_type>1</edge_type>
          <source_obj>138</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_96">
          <id>260</id>
          <edge_type>1</edge_type>
          <source_obj>140</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_97">
          <id>261</id>
          <edge_type>1</edge_type>
          <source_obj>142</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_98">
          <id>262</id>
          <edge_type>1</edge_type>
          <source_obj>144</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_99">
          <id>263</id>
          <edge_type>1</edge_type>
          <source_obj>146</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_100">
          <id>264</id>
          <edge_type>1</edge_type>
          <source_obj>148</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_101">
          <id>265</id>
          <edge_type>1</edge_type>
          <source_obj>150</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_102">
          <id>266</id>
          <edge_type>1</edge_type>
          <source_obj>152</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_103">
          <id>267</id>
          <edge_type>1</edge_type>
          <source_obj>154</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_104">
          <id>268</id>
          <edge_type>1</edge_type>
          <source_obj>156</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_105">
          <id>269</id>
          <edge_type>1</edge_type>
          <source_obj>158</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_106">
          <id>270</id>
          <edge_type>1</edge_type>
          <source_obj>160</source_obj>
          <sink_obj>179</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_107">
        <mId>1</mId>
        <mTag>LSTM_Top</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>181</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>413741</mMinLatency>
        <mMaxLatency>413745</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_108">
      <states class_id="25" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_109">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_110">
          <id>2</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_111">
              <id>179</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_112">
          <id>3</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_113">
              <id>179</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_114">
          <id>4</id>
          <operations>
            <count>19</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_115">
              <id>161</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_116">
              <id>162</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_117">
              <id>163</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_118">
              <id>164</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_119">
              <id>165</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_120">
              <id>166</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_121">
              <id>167</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_122">
              <id>168</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_123">
              <id>169</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_124">
              <id>170</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_125">
              <id>171</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_126">
              <id>172</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_127">
              <id>173</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_128">
              <id>174</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_129">
              <id>175</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_130">
              <id>176</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_131">
              <id>177</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_132">
              <id>178</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_133">
              <id>180</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_134">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>-1</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_135">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_136">
          <inState>3</inState>
          <outState>4</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="34" tracking_level="1" version="0" object_id="_137">
      <dp_component_resource class_id="35" tracking_level="0" version="0">
        <count>15</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="0" version="0">
          <first>grp_lipnet_lstm_fu_196 (lipnet_lstm)</first>
          <second class_id="37" tracking_level="0" version="0">
            <count>5</count>
            <item_version>0</item_version>
            <item class_id="38" tracking_level="0" version="0">
              <first>BRAM</first>
              <second>88</second>
            </item>
            <item>
              <first>DSP48E</first>
              <second>175</second>
            </item>
            <item>
              <first>FF</first>
              <second>46295</second>
            </item>
            <item>
              <first>LUT</first>
              <second>48916</second>
            </item>
            <item>
              <first>URAM</first>
              <second>0</second>
            </item>
          </second>
        </item>
        <item>
          <first>regslice_both_in_data_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_dest_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_id_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_keep_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_last_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_strb_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_user_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_data_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_dest_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_id_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_keep_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_last_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_strb_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_user_V_U (regslice_both)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>grp_lipnet_lstm_fu_196_out_r_TREADY ( and ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>5</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>5</second>
            </item>
            <item>
              <first>LUT</first>
              <second>27</second>
            </item>
          </second>
        </item>
        <item>
          <first>in_r_TREADY_int</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>2</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>4</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>4</second>
            </item>
          </second>
        </item>
        <item>
          <first>grp_lipnet_lstm_fu_196_ap_start_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>15</count>
        <item_version>0</item_version>
        <item>
          <first>grp_lipnet_lstm_fu_196</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_data_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_dest_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_id_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_keep_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_last_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_strb_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_in_user_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_data_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_dest_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_id_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_keep_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_last_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_strb_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>regslice_both_out_user_V_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="39" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="40" tracking_level="0" version="0">
          <first>grp_lipnet_lstm_fu_196 (lipnet_lstm)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>179</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="41" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="42" tracking_level="0" version="0">
        <first>179</first>
        <second class_id="43" tracking_level="0" version="0">
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>180</first>
        <second>
          <first>3</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="44" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="45" tracking_level="0" version="0">
        <first>181</first>
        <second class_id="46" tracking_level="0" version="0">
          <first>0</first>
          <second>3</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="47" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </regions>
    <dp_fu_nodes class_id="48" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="49" tracking_level="0" version="0">
        <first>196</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>179</item>
          <item>179</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="51" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>grp_lipnet_lstm_fu_196</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>179</item>
          <item>179</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="53" tracking_level="0" version="0">
      <count>73</count>
      <item_version>0</item_version>
      <item class_id="54" tracking_level="0" version="0">
        <first class_id="55" tracking_level="0" version="0">
          <first>Bias0_c</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Bias0_f</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Bias0_i</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Bias0_o</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Bias_lc</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight0_c</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight0_f</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight0_i</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight0_o</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_0</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_10</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_11</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_12</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_13</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_14</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_15</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_16</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_17</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_18</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_19</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_20</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_21</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_22</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_23</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_24</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_25</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_26</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_27</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_28</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_29</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_30</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_31</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_32</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_33</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_34</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_35</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_36</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_37</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_38</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_39</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_40</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_41</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_42</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_43</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_44</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_45</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_46</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_47</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_48</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_49</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_50</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_51</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_52</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_53</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_54</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_55</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_56</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_57</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_58</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_59</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_60</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_61</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_62</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_63</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_7</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_8</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
      <item>
        <first>
          <first>Weight_lc_9</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>179</item>
        </second>
      </item>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="56" tracking_level="0" version="0">
      <count>14</count>
      <item_version>0</item_version>
      <item class_id="57" tracking_level="0" version="0">
        <first>in_data_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>in_dest_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>in_id_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>in_keep_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>in_last_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>in_strb_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>in_user_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>out_data_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>out_dest_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>out_id_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>out_keep_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>out_last_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>out_strb_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>out_user_V</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>179</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core class_id="58" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
