// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sigmoid.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sigmoid::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sigmoid::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> sigmoid::ap_ST_fsm_state1 = "1";
const sc_lv<3> sigmoid::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> sigmoid::ap_ST_fsm_state61 = "100";
const bool sigmoid::ap_const_boolean_1 = true;
const sc_lv<32> sigmoid::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> sigmoid::ap_const_lv32_1 = "1";
const bool sigmoid::ap_const_boolean_0 = false;
const sc_lv<1> sigmoid::ap_const_lv1_0 = "0";
const sc_lv<1> sigmoid::ap_const_lv1_1 = "1";
const sc_lv<7> sigmoid::ap_const_lv7_0 = "0000000";
const sc_lv<64> sigmoid::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<7> sigmoid::ap_const_lv7_40 = "1000000";
const sc_lv<7> sigmoid::ap_const_lv7_1 = "1";
const sc_lv<32> sigmoid::ap_const_lv32_80000000 = "10000000000000000000000000000000";
const sc_lv<32> sigmoid::ap_const_lv32_2 = "10";
const sc_lv<64> sigmoid::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";

sigmoid::sigmoid(sc_module_name name) : sc_module(name), mVcdFile(0) {
    LSTM_Top_fptrunc_dEe_U13 = new LSTM_Top_fptrunc_dEe<1,2,64,32>("LSTM_Top_fptrunc_dEe_U13");
    LSTM_Top_fptrunc_dEe_U13->clk(ap_clk);
    LSTM_Top_fptrunc_dEe_U13->reset(ap_rst);
    LSTM_Top_fptrunc_dEe_U13->din0(tmp_2_reg_170);
    LSTM_Top_fptrunc_dEe_U13->ce(ap_var_for_const0);
    LSTM_Top_fptrunc_dEe_U13->dout(grp_fu_77_p1);
    LSTM_Top_fpext_32eOg_U14 = new LSTM_Top_fpext_32eOg<1,2,32,64>("LSTM_Top_fpext_32eOg_U14");
    LSTM_Top_fpext_32eOg_U14->clk(ap_clk);
    LSTM_Top_fpext_32eOg_U14->reset(ap_rst);
    LSTM_Top_fpext_32eOg_U14->din0(grp_fu_81_p0);
    LSTM_Top_fpext_32eOg_U14->ce(ap_var_for_const0);
    LSTM_Top_fpext_32eOg_U14->dout(grp_fu_81_p1);
    LSTM_Top_dadd_64nfYi_U15 = new LSTM_Top_dadd_64nfYi<1,5,64,64,64>("LSTM_Top_dadd_64nfYi_U15");
    LSTM_Top_dadd_64nfYi_U15->clk(ap_clk);
    LSTM_Top_dadd_64nfYi_U15->reset(ap_rst);
    LSTM_Top_dadd_64nfYi_U15->din0(tmp_s_reg_160);
    LSTM_Top_dadd_64nfYi_U15->din1(ap_var_for_const1);
    LSTM_Top_dadd_64nfYi_U15->ce(ap_var_for_const0);
    LSTM_Top_dadd_64nfYi_U15->dout(grp_fu_84_p2);
    LSTM_Top_ddiv_64ng8j_U16 = new LSTM_Top_ddiv_64ng8j<1,31,64,64,64>("LSTM_Top_ddiv_64ng8j_U16");
    LSTM_Top_ddiv_64ng8j_U16->clk(ap_clk);
    LSTM_Top_ddiv_64ng8j_U16->reset(ap_rst);
    LSTM_Top_ddiv_64ng8j_U16->din0(ap_var_for_const1);
    LSTM_Top_ddiv_64ng8j_U16->din1(tmp_1_reg_165);
    LSTM_Top_ddiv_64ng8j_U16->ce(ap_var_for_const0);
    LSTM_Top_ddiv_64ng8j_U16->dout(grp_fu_89_p2);
    LSTM_Top_dexp_64nhbi_U17 = new LSTM_Top_dexp_64nhbi<1,18,64,64,64>("LSTM_Top_dexp_64nhbi_U17");
    LSTM_Top_dexp_64nhbi_U17->clk(ap_clk);
    LSTM_Top_dexp_64nhbi_U17->reset(ap_rst);
    LSTM_Top_dexp_64nhbi_U17->din0(ap_var_for_const2);
    LSTM_Top_dexp_64nhbi_U17->din1(tmp_9_reg_155);
    LSTM_Top_dexp_64nhbi_U17->ce(ap_var_for_const0);
    LSTM_Top_dexp_64nhbi_U17->dout(grp_fu_94_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln79_fu_111_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state61);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter14);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter15);

    SC_METHOD(thread_ap_block_state18_pp0_stage0_iter16);

    SC_METHOD(thread_ap_block_state19_pp0_stage0_iter17);

    SC_METHOD(thread_ap_block_state20_pp0_stage0_iter18);

    SC_METHOD(thread_ap_block_state21_pp0_stage0_iter19);

    SC_METHOD(thread_ap_block_state22_pp0_stage0_iter20);

    SC_METHOD(thread_ap_block_state23_pp0_stage0_iter21);

    SC_METHOD(thread_ap_block_state24_pp0_stage0_iter22);

    SC_METHOD(thread_ap_block_state25_pp0_stage0_iter23);

    SC_METHOD(thread_ap_block_state26_pp0_stage0_iter24);

    SC_METHOD(thread_ap_block_state27_pp0_stage0_iter25);

    SC_METHOD(thread_ap_block_state28_pp0_stage0_iter26);

    SC_METHOD(thread_ap_block_state29_pp0_stage0_iter27);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state30_pp0_stage0_iter28);

    SC_METHOD(thread_ap_block_state31_pp0_stage0_iter29);

    SC_METHOD(thread_ap_block_state32_pp0_stage0_iter30);

    SC_METHOD(thread_ap_block_state33_pp0_stage0_iter31);

    SC_METHOD(thread_ap_block_state34_pp0_stage0_iter32);

    SC_METHOD(thread_ap_block_state35_pp0_stage0_iter33);

    SC_METHOD(thread_ap_block_state36_pp0_stage0_iter34);

    SC_METHOD(thread_ap_block_state37_pp0_stage0_iter35);

    SC_METHOD(thread_ap_block_state38_pp0_stage0_iter36);

    SC_METHOD(thread_ap_block_state39_pp0_stage0_iter37);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state40_pp0_stage0_iter38);

    SC_METHOD(thread_ap_block_state41_pp0_stage0_iter39);

    SC_METHOD(thread_ap_block_state42_pp0_stage0_iter40);

    SC_METHOD(thread_ap_block_state43_pp0_stage0_iter41);

    SC_METHOD(thread_ap_block_state44_pp0_stage0_iter42);

    SC_METHOD(thread_ap_block_state45_pp0_stage0_iter43);

    SC_METHOD(thread_ap_block_state46_pp0_stage0_iter44);

    SC_METHOD(thread_ap_block_state47_pp0_stage0_iter45);

    SC_METHOD(thread_ap_block_state48_pp0_stage0_iter46);

    SC_METHOD(thread_ap_block_state49_pp0_stage0_iter47);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state50_pp0_stage0_iter48);

    SC_METHOD(thread_ap_block_state51_pp0_stage0_iter49);

    SC_METHOD(thread_ap_block_state52_pp0_stage0_iter50);

    SC_METHOD(thread_ap_block_state53_pp0_stage0_iter51);

    SC_METHOD(thread_ap_block_state54_pp0_stage0_iter52);

    SC_METHOD(thread_ap_block_state55_pp0_stage0_iter53);

    SC_METHOD(thread_ap_block_state56_pp0_stage0_iter54);

    SC_METHOD(thread_ap_block_state57_pp0_stage0_iter55);

    SC_METHOD(thread_ap_block_state58_pp0_stage0_iter56);

    SC_METHOD(thread_ap_block_state59_pp0_stage0_iter57);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state60_pp0_stage0_iter58);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter7);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln76_fu_99_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state61 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_enable_reg_pp0_iter17 );
    sensitive << ( ap_enable_reg_pp0_iter18 );
    sensitive << ( ap_enable_reg_pp0_iter19 );
    sensitive << ( ap_enable_reg_pp0_iter20 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( ap_enable_reg_pp0_iter22 );
    sensitive << ( ap_enable_reg_pp0_iter23 );
    sensitive << ( ap_enable_reg_pp0_iter24 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( ap_enable_reg_pp0_iter26 );
    sensitive << ( ap_enable_reg_pp0_iter27 );
    sensitive << ( ap_enable_reg_pp0_iter28 );
    sensitive << ( ap_enable_reg_pp0_iter29 );
    sensitive << ( ap_enable_reg_pp0_iter30 );
    sensitive << ( ap_enable_reg_pp0_iter31 );
    sensitive << ( ap_enable_reg_pp0_iter32 );
    sensitive << ( ap_enable_reg_pp0_iter33 );
    sensitive << ( ap_enable_reg_pp0_iter34 );
    sensitive << ( ap_enable_reg_pp0_iter35 );
    sensitive << ( ap_enable_reg_pp0_iter36 );
    sensitive << ( ap_enable_reg_pp0_iter37 );
    sensitive << ( ap_enable_reg_pp0_iter38 );
    sensitive << ( ap_enable_reg_pp0_iter39 );
    sensitive << ( ap_enable_reg_pp0_iter40 );
    sensitive << ( ap_enable_reg_pp0_iter41 );
    sensitive << ( ap_enable_reg_pp0_iter42 );
    sensitive << ( ap_enable_reg_pp0_iter43 );
    sensitive << ( ap_enable_reg_pp0_iter44 );
    sensitive << ( ap_enable_reg_pp0_iter45 );
    sensitive << ( ap_enable_reg_pp0_iter46 );
    sensitive << ( ap_enable_reg_pp0_iter47 );
    sensitive << ( ap_enable_reg_pp0_iter48 );
    sensitive << ( ap_enable_reg_pp0_iter49 );
    sensitive << ( ap_enable_reg_pp0_iter50 );
    sensitive << ( ap_enable_reg_pp0_iter51 );
    sensitive << ( ap_enable_reg_pp0_iter52 );
    sensitive << ( ap_enable_reg_pp0_iter53 );
    sensitive << ( ap_enable_reg_pp0_iter54 );
    sensitive << ( ap_enable_reg_pp0_iter55 );
    sensitive << ( ap_enable_reg_pp0_iter56 );
    sensitive << ( ap_enable_reg_pp0_iter57 );
    sensitive << ( ap_enable_reg_pp0_iter58 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state61 );

    SC_METHOD(thread_bitcast_ln79_fu_116_p1);
    sensitive << ( a_q0 );

    SC_METHOD(thread_grp_fu_81_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( xor_ln79_fu_120_p2 );

    SC_METHOD(thread_i_fu_105_p2);
    sensitive << ( i_0_reg_66 );

    SC_METHOD(thread_icmp_ln76_fu_99_p2);
    sensitive << ( i_0_reg_66 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_res_address0);
    sensitive << ( zext_ln79_reg_140_pp0_iter57_reg );
    sensitive << ( ap_enable_reg_pp0_iter58 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_res_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter58 );

    SC_METHOD(thread_res_d0);
    sensitive << ( ap_enable_reg_pp0_iter58 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( grp_fu_77_p1 );

    SC_METHOD(thread_res_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln76_reg_131_pp0_iter57_reg );
    sensitive << ( ap_enable_reg_pp0_iter58 );

    SC_METHOD(thread_xor_ln79_fu_120_p2);
    sensitive << ( bitcast_ln79_fu_116_p1 );

    SC_METHOD(thread_zext_ln79_fu_111_p1);
    sensitive << ( i_0_reg_66 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln76_fu_99_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter57 );
    sensitive << ( ap_enable_reg_pp0_iter58 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter15 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter16 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter17 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter18 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter19 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter20 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter21 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter22 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter23 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter24 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter25 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter26 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter27 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter28 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter29 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter30 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter31 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter32 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter33 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter34 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter35 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter36 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter37 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter38 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter39 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter40 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter41 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter42 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter43 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter44 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter45 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter46 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter47 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter48 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter49 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter50 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter51 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter52 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter53 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter54 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter55 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter56 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter57 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter58 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sigmoid_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, res_address0, "(port)res_address0");
    sc_trace(mVcdFile, res_ce0, "(port)res_ce0");
    sc_trace(mVcdFile, res_we0, "(port)res_we0");
    sc_trace(mVcdFile, res_d0, "(port)res_d0");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_0_reg_66, "i_0_reg_66");
    sc_trace(mVcdFile, icmp_ln76_fu_99_p2, "icmp_ln76_fu_99_p2");
    sc_trace(mVcdFile, icmp_ln76_reg_131, "icmp_ln76_reg_131");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter5, "ap_block_state7_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter6, "ap_block_state8_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter7, "ap_block_state9_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter8, "ap_block_state10_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter9, "ap_block_state11_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter10, "ap_block_state12_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter11, "ap_block_state13_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter12, "ap_block_state14_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter13, "ap_block_state15_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter14, "ap_block_state16_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter15, "ap_block_state17_pp0_stage0_iter15");
    sc_trace(mVcdFile, ap_block_state18_pp0_stage0_iter16, "ap_block_state18_pp0_stage0_iter16");
    sc_trace(mVcdFile, ap_block_state19_pp0_stage0_iter17, "ap_block_state19_pp0_stage0_iter17");
    sc_trace(mVcdFile, ap_block_state20_pp0_stage0_iter18, "ap_block_state20_pp0_stage0_iter18");
    sc_trace(mVcdFile, ap_block_state21_pp0_stage0_iter19, "ap_block_state21_pp0_stage0_iter19");
    sc_trace(mVcdFile, ap_block_state22_pp0_stage0_iter20, "ap_block_state22_pp0_stage0_iter20");
    sc_trace(mVcdFile, ap_block_state23_pp0_stage0_iter21, "ap_block_state23_pp0_stage0_iter21");
    sc_trace(mVcdFile, ap_block_state24_pp0_stage0_iter22, "ap_block_state24_pp0_stage0_iter22");
    sc_trace(mVcdFile, ap_block_state25_pp0_stage0_iter23, "ap_block_state25_pp0_stage0_iter23");
    sc_trace(mVcdFile, ap_block_state26_pp0_stage0_iter24, "ap_block_state26_pp0_stage0_iter24");
    sc_trace(mVcdFile, ap_block_state27_pp0_stage0_iter25, "ap_block_state27_pp0_stage0_iter25");
    sc_trace(mVcdFile, ap_block_state28_pp0_stage0_iter26, "ap_block_state28_pp0_stage0_iter26");
    sc_trace(mVcdFile, ap_block_state29_pp0_stage0_iter27, "ap_block_state29_pp0_stage0_iter27");
    sc_trace(mVcdFile, ap_block_state30_pp0_stage0_iter28, "ap_block_state30_pp0_stage0_iter28");
    sc_trace(mVcdFile, ap_block_state31_pp0_stage0_iter29, "ap_block_state31_pp0_stage0_iter29");
    sc_trace(mVcdFile, ap_block_state32_pp0_stage0_iter30, "ap_block_state32_pp0_stage0_iter30");
    sc_trace(mVcdFile, ap_block_state33_pp0_stage0_iter31, "ap_block_state33_pp0_stage0_iter31");
    sc_trace(mVcdFile, ap_block_state34_pp0_stage0_iter32, "ap_block_state34_pp0_stage0_iter32");
    sc_trace(mVcdFile, ap_block_state35_pp0_stage0_iter33, "ap_block_state35_pp0_stage0_iter33");
    sc_trace(mVcdFile, ap_block_state36_pp0_stage0_iter34, "ap_block_state36_pp0_stage0_iter34");
    sc_trace(mVcdFile, ap_block_state37_pp0_stage0_iter35, "ap_block_state37_pp0_stage0_iter35");
    sc_trace(mVcdFile, ap_block_state38_pp0_stage0_iter36, "ap_block_state38_pp0_stage0_iter36");
    sc_trace(mVcdFile, ap_block_state39_pp0_stage0_iter37, "ap_block_state39_pp0_stage0_iter37");
    sc_trace(mVcdFile, ap_block_state40_pp0_stage0_iter38, "ap_block_state40_pp0_stage0_iter38");
    sc_trace(mVcdFile, ap_block_state41_pp0_stage0_iter39, "ap_block_state41_pp0_stage0_iter39");
    sc_trace(mVcdFile, ap_block_state42_pp0_stage0_iter40, "ap_block_state42_pp0_stage0_iter40");
    sc_trace(mVcdFile, ap_block_state43_pp0_stage0_iter41, "ap_block_state43_pp0_stage0_iter41");
    sc_trace(mVcdFile, ap_block_state44_pp0_stage0_iter42, "ap_block_state44_pp0_stage0_iter42");
    sc_trace(mVcdFile, ap_block_state45_pp0_stage0_iter43, "ap_block_state45_pp0_stage0_iter43");
    sc_trace(mVcdFile, ap_block_state46_pp0_stage0_iter44, "ap_block_state46_pp0_stage0_iter44");
    sc_trace(mVcdFile, ap_block_state47_pp0_stage0_iter45, "ap_block_state47_pp0_stage0_iter45");
    sc_trace(mVcdFile, ap_block_state48_pp0_stage0_iter46, "ap_block_state48_pp0_stage0_iter46");
    sc_trace(mVcdFile, ap_block_state49_pp0_stage0_iter47, "ap_block_state49_pp0_stage0_iter47");
    sc_trace(mVcdFile, ap_block_state50_pp0_stage0_iter48, "ap_block_state50_pp0_stage0_iter48");
    sc_trace(mVcdFile, ap_block_state51_pp0_stage0_iter49, "ap_block_state51_pp0_stage0_iter49");
    sc_trace(mVcdFile, ap_block_state52_pp0_stage0_iter50, "ap_block_state52_pp0_stage0_iter50");
    sc_trace(mVcdFile, ap_block_state53_pp0_stage0_iter51, "ap_block_state53_pp0_stage0_iter51");
    sc_trace(mVcdFile, ap_block_state54_pp0_stage0_iter52, "ap_block_state54_pp0_stage0_iter52");
    sc_trace(mVcdFile, ap_block_state55_pp0_stage0_iter53, "ap_block_state55_pp0_stage0_iter53");
    sc_trace(mVcdFile, ap_block_state56_pp0_stage0_iter54, "ap_block_state56_pp0_stage0_iter54");
    sc_trace(mVcdFile, ap_block_state57_pp0_stage0_iter55, "ap_block_state57_pp0_stage0_iter55");
    sc_trace(mVcdFile, ap_block_state58_pp0_stage0_iter56, "ap_block_state58_pp0_stage0_iter56");
    sc_trace(mVcdFile, ap_block_state59_pp0_stage0_iter57, "ap_block_state59_pp0_stage0_iter57");
    sc_trace(mVcdFile, ap_block_state60_pp0_stage0_iter58, "ap_block_state60_pp0_stage0_iter58");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter1_reg, "icmp_ln76_reg_131_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter2_reg, "icmp_ln76_reg_131_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter3_reg, "icmp_ln76_reg_131_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter4_reg, "icmp_ln76_reg_131_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter5_reg, "icmp_ln76_reg_131_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter6_reg, "icmp_ln76_reg_131_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter7_reg, "icmp_ln76_reg_131_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter8_reg, "icmp_ln76_reg_131_pp0_iter8_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter9_reg, "icmp_ln76_reg_131_pp0_iter9_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter10_reg, "icmp_ln76_reg_131_pp0_iter10_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter11_reg, "icmp_ln76_reg_131_pp0_iter11_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter12_reg, "icmp_ln76_reg_131_pp0_iter12_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter13_reg, "icmp_ln76_reg_131_pp0_iter13_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter14_reg, "icmp_ln76_reg_131_pp0_iter14_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter15_reg, "icmp_ln76_reg_131_pp0_iter15_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter16_reg, "icmp_ln76_reg_131_pp0_iter16_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter17_reg, "icmp_ln76_reg_131_pp0_iter17_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter18_reg, "icmp_ln76_reg_131_pp0_iter18_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter19_reg, "icmp_ln76_reg_131_pp0_iter19_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter20_reg, "icmp_ln76_reg_131_pp0_iter20_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter21_reg, "icmp_ln76_reg_131_pp0_iter21_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter22_reg, "icmp_ln76_reg_131_pp0_iter22_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter23_reg, "icmp_ln76_reg_131_pp0_iter23_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter24_reg, "icmp_ln76_reg_131_pp0_iter24_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter25_reg, "icmp_ln76_reg_131_pp0_iter25_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter26_reg, "icmp_ln76_reg_131_pp0_iter26_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter27_reg, "icmp_ln76_reg_131_pp0_iter27_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter28_reg, "icmp_ln76_reg_131_pp0_iter28_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter29_reg, "icmp_ln76_reg_131_pp0_iter29_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter30_reg, "icmp_ln76_reg_131_pp0_iter30_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter31_reg, "icmp_ln76_reg_131_pp0_iter31_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter32_reg, "icmp_ln76_reg_131_pp0_iter32_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter33_reg, "icmp_ln76_reg_131_pp0_iter33_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter34_reg, "icmp_ln76_reg_131_pp0_iter34_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter35_reg, "icmp_ln76_reg_131_pp0_iter35_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter36_reg, "icmp_ln76_reg_131_pp0_iter36_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter37_reg, "icmp_ln76_reg_131_pp0_iter37_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter38_reg, "icmp_ln76_reg_131_pp0_iter38_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter39_reg, "icmp_ln76_reg_131_pp0_iter39_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter40_reg, "icmp_ln76_reg_131_pp0_iter40_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter41_reg, "icmp_ln76_reg_131_pp0_iter41_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter42_reg, "icmp_ln76_reg_131_pp0_iter42_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter43_reg, "icmp_ln76_reg_131_pp0_iter43_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter44_reg, "icmp_ln76_reg_131_pp0_iter44_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter45_reg, "icmp_ln76_reg_131_pp0_iter45_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter46_reg, "icmp_ln76_reg_131_pp0_iter46_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter47_reg, "icmp_ln76_reg_131_pp0_iter47_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter48_reg, "icmp_ln76_reg_131_pp0_iter48_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter49_reg, "icmp_ln76_reg_131_pp0_iter49_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter50_reg, "icmp_ln76_reg_131_pp0_iter50_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter51_reg, "icmp_ln76_reg_131_pp0_iter51_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter52_reg, "icmp_ln76_reg_131_pp0_iter52_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter53_reg, "icmp_ln76_reg_131_pp0_iter53_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter54_reg, "icmp_ln76_reg_131_pp0_iter54_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter55_reg, "icmp_ln76_reg_131_pp0_iter55_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter56_reg, "icmp_ln76_reg_131_pp0_iter56_reg");
    sc_trace(mVcdFile, icmp_ln76_reg_131_pp0_iter57_reg, "icmp_ln76_reg_131_pp0_iter57_reg");
    sc_trace(mVcdFile, i_fu_105_p2, "i_fu_105_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, zext_ln79_fu_111_p1, "zext_ln79_fu_111_p1");
    sc_trace(mVcdFile, zext_ln79_reg_140, "zext_ln79_reg_140");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter1_reg, "zext_ln79_reg_140_pp0_iter1_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter2_reg, "zext_ln79_reg_140_pp0_iter2_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter3_reg, "zext_ln79_reg_140_pp0_iter3_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter4_reg, "zext_ln79_reg_140_pp0_iter4_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter5_reg, "zext_ln79_reg_140_pp0_iter5_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter6_reg, "zext_ln79_reg_140_pp0_iter6_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter7_reg, "zext_ln79_reg_140_pp0_iter7_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter8_reg, "zext_ln79_reg_140_pp0_iter8_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter9_reg, "zext_ln79_reg_140_pp0_iter9_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter10_reg, "zext_ln79_reg_140_pp0_iter10_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter11_reg, "zext_ln79_reg_140_pp0_iter11_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter12_reg, "zext_ln79_reg_140_pp0_iter12_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter13_reg, "zext_ln79_reg_140_pp0_iter13_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter14_reg, "zext_ln79_reg_140_pp0_iter14_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter15_reg, "zext_ln79_reg_140_pp0_iter15_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter16_reg, "zext_ln79_reg_140_pp0_iter16_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter17_reg, "zext_ln79_reg_140_pp0_iter17_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter18_reg, "zext_ln79_reg_140_pp0_iter18_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter19_reg, "zext_ln79_reg_140_pp0_iter19_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter20_reg, "zext_ln79_reg_140_pp0_iter20_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter21_reg, "zext_ln79_reg_140_pp0_iter21_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter22_reg, "zext_ln79_reg_140_pp0_iter22_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter23_reg, "zext_ln79_reg_140_pp0_iter23_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter24_reg, "zext_ln79_reg_140_pp0_iter24_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter25_reg, "zext_ln79_reg_140_pp0_iter25_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter26_reg, "zext_ln79_reg_140_pp0_iter26_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter27_reg, "zext_ln79_reg_140_pp0_iter27_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter28_reg, "zext_ln79_reg_140_pp0_iter28_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter29_reg, "zext_ln79_reg_140_pp0_iter29_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter30_reg, "zext_ln79_reg_140_pp0_iter30_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter31_reg, "zext_ln79_reg_140_pp0_iter31_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter32_reg, "zext_ln79_reg_140_pp0_iter32_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter33_reg, "zext_ln79_reg_140_pp0_iter33_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter34_reg, "zext_ln79_reg_140_pp0_iter34_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter35_reg, "zext_ln79_reg_140_pp0_iter35_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter36_reg, "zext_ln79_reg_140_pp0_iter36_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter37_reg, "zext_ln79_reg_140_pp0_iter37_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter38_reg, "zext_ln79_reg_140_pp0_iter38_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter39_reg, "zext_ln79_reg_140_pp0_iter39_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter40_reg, "zext_ln79_reg_140_pp0_iter40_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter41_reg, "zext_ln79_reg_140_pp0_iter41_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter42_reg, "zext_ln79_reg_140_pp0_iter42_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter43_reg, "zext_ln79_reg_140_pp0_iter43_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter44_reg, "zext_ln79_reg_140_pp0_iter44_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter45_reg, "zext_ln79_reg_140_pp0_iter45_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter46_reg, "zext_ln79_reg_140_pp0_iter46_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter47_reg, "zext_ln79_reg_140_pp0_iter47_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter48_reg, "zext_ln79_reg_140_pp0_iter48_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter49_reg, "zext_ln79_reg_140_pp0_iter49_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter50_reg, "zext_ln79_reg_140_pp0_iter50_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter51_reg, "zext_ln79_reg_140_pp0_iter51_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter52_reg, "zext_ln79_reg_140_pp0_iter52_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter53_reg, "zext_ln79_reg_140_pp0_iter53_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter54_reg, "zext_ln79_reg_140_pp0_iter54_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter55_reg, "zext_ln79_reg_140_pp0_iter55_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter56_reg, "zext_ln79_reg_140_pp0_iter56_reg");
    sc_trace(mVcdFile, zext_ln79_reg_140_pp0_iter57_reg, "zext_ln79_reg_140_pp0_iter57_reg");
    sc_trace(mVcdFile, grp_fu_81_p1, "grp_fu_81_p1");
    sc_trace(mVcdFile, tmp_9_reg_155, "tmp_9_reg_155");
    sc_trace(mVcdFile, grp_fu_94_p2, "grp_fu_94_p2");
    sc_trace(mVcdFile, tmp_s_reg_160, "tmp_s_reg_160");
    sc_trace(mVcdFile, grp_fu_84_p2, "grp_fu_84_p2");
    sc_trace(mVcdFile, tmp_1_reg_165, "tmp_1_reg_165");
    sc_trace(mVcdFile, grp_fu_89_p2, "grp_fu_89_p2");
    sc_trace(mVcdFile, tmp_2_reg_170, "tmp_2_reg_170");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter15, "ap_enable_reg_pp0_iter15");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter16, "ap_enable_reg_pp0_iter16");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter17, "ap_enable_reg_pp0_iter17");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter18, "ap_enable_reg_pp0_iter18");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter19, "ap_enable_reg_pp0_iter19");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter20, "ap_enable_reg_pp0_iter20");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter21, "ap_enable_reg_pp0_iter21");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter22, "ap_enable_reg_pp0_iter22");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter23, "ap_enable_reg_pp0_iter23");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter24, "ap_enable_reg_pp0_iter24");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter25, "ap_enable_reg_pp0_iter25");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter26, "ap_enable_reg_pp0_iter26");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter27, "ap_enable_reg_pp0_iter27");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter28, "ap_enable_reg_pp0_iter28");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter29, "ap_enable_reg_pp0_iter29");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter30, "ap_enable_reg_pp0_iter30");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter31, "ap_enable_reg_pp0_iter31");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter32, "ap_enable_reg_pp0_iter32");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter33, "ap_enable_reg_pp0_iter33");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter34, "ap_enable_reg_pp0_iter34");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter35, "ap_enable_reg_pp0_iter35");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter36, "ap_enable_reg_pp0_iter36");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter37, "ap_enable_reg_pp0_iter37");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter38, "ap_enable_reg_pp0_iter38");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter39, "ap_enable_reg_pp0_iter39");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter40, "ap_enable_reg_pp0_iter40");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter41, "ap_enable_reg_pp0_iter41");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter42, "ap_enable_reg_pp0_iter42");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter43, "ap_enable_reg_pp0_iter43");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter44, "ap_enable_reg_pp0_iter44");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter45, "ap_enable_reg_pp0_iter45");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter46, "ap_enable_reg_pp0_iter46");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter47, "ap_enable_reg_pp0_iter47");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter48, "ap_enable_reg_pp0_iter48");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter49, "ap_enable_reg_pp0_iter49");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter50, "ap_enable_reg_pp0_iter50");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter51, "ap_enable_reg_pp0_iter51");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter52, "ap_enable_reg_pp0_iter52");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter53, "ap_enable_reg_pp0_iter53");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter54, "ap_enable_reg_pp0_iter54");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter55, "ap_enable_reg_pp0_iter55");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter56, "ap_enable_reg_pp0_iter56");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter57, "ap_enable_reg_pp0_iter57");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter58, "ap_enable_reg_pp0_iter58");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, grp_fu_77_p1, "grp_fu_77_p1");
    sc_trace(mVcdFile, grp_fu_81_p0, "grp_fu_81_p0");
    sc_trace(mVcdFile, bitcast_ln79_fu_116_p1, "bitcast_ln79_fu_116_p1");
    sc_trace(mVcdFile, xor_ln79_fu_120_p2, "xor_ln79_fu_120_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state61, "ap_CS_fsm_state61");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

sigmoid::~sigmoid() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete LSTM_Top_fptrunc_dEe_U13;
    delete LSTM_Top_fpext_32eOg_U14;
    delete LSTM_Top_dadd_64nfYi_U15;
    delete LSTM_Top_ddiv_64ng8j_U16;
    delete LSTM_Top_dexp_64nhbi_U17;
}

void sigmoid::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sigmoid::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3FF0000000000000;
}

void sigmoid::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv64_0;
}

void sigmoid::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter15 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter15 = ap_enable_reg_pp0_iter14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter16 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter16 = ap_enable_reg_pp0_iter15.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter17 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter17 = ap_enable_reg_pp0_iter16.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter18 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter18 = ap_enable_reg_pp0_iter17.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter19 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter19 = ap_enable_reg_pp0_iter18.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter20 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter20 = ap_enable_reg_pp0_iter19.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter21 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter21 = ap_enable_reg_pp0_iter20.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter22 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter22 = ap_enable_reg_pp0_iter21.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter23 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter23 = ap_enable_reg_pp0_iter22.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter24 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter24 = ap_enable_reg_pp0_iter23.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter25 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter25 = ap_enable_reg_pp0_iter24.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter26 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter26 = ap_enable_reg_pp0_iter25.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter27 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter27 = ap_enable_reg_pp0_iter26.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter28 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter28 = ap_enable_reg_pp0_iter27.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter29 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter29 = ap_enable_reg_pp0_iter28.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter30 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter30 = ap_enable_reg_pp0_iter29.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter31 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter31 = ap_enable_reg_pp0_iter30.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter32 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter32 = ap_enable_reg_pp0_iter31.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter33 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter33 = ap_enable_reg_pp0_iter32.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter34 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter34 = ap_enable_reg_pp0_iter33.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter35 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter35 = ap_enable_reg_pp0_iter34.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter36 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter36 = ap_enable_reg_pp0_iter35.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter37 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter37 = ap_enable_reg_pp0_iter36.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter38 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter38 = ap_enable_reg_pp0_iter37.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter39 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter39 = ap_enable_reg_pp0_iter38.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter40 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter40 = ap_enable_reg_pp0_iter39.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter41 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter41 = ap_enable_reg_pp0_iter40.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter42 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter42 = ap_enable_reg_pp0_iter41.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter43 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter43 = ap_enable_reg_pp0_iter42.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter44 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter44 = ap_enable_reg_pp0_iter43.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter45 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter45 = ap_enable_reg_pp0_iter44.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter46 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter46 = ap_enable_reg_pp0_iter45.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter47 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter47 = ap_enable_reg_pp0_iter46.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter48 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter48 = ap_enable_reg_pp0_iter47.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter49 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter49 = ap_enable_reg_pp0_iter48.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter50 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter50 = ap_enable_reg_pp0_iter49.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter51 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter51 = ap_enable_reg_pp0_iter50.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter52 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter52 = ap_enable_reg_pp0_iter51.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter53 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter53 = ap_enable_reg_pp0_iter52.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter54 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter54 = ap_enable_reg_pp0_iter53.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter55 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter55 = ap_enable_reg_pp0_iter54.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter56 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter56 = ap_enable_reg_pp0_iter55.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter57 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter57 = ap_enable_reg_pp0_iter56.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter58 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter58 = ap_enable_reg_pp0_iter57.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter58 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln76_fu_99_p2.read(), ap_const_lv1_0))) {
        i_0_reg_66 = i_fu_105_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_66 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln76_reg_131 = icmp_ln76_fu_99_p2.read();
        icmp_ln76_reg_131_pp0_iter1_reg = icmp_ln76_reg_131.read();
        zext_ln79_reg_140_pp0_iter1_reg = zext_ln79_reg_140.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln76_reg_131_pp0_iter10_reg = icmp_ln76_reg_131_pp0_iter9_reg.read();
        icmp_ln76_reg_131_pp0_iter11_reg = icmp_ln76_reg_131_pp0_iter10_reg.read();
        icmp_ln76_reg_131_pp0_iter12_reg = icmp_ln76_reg_131_pp0_iter11_reg.read();
        icmp_ln76_reg_131_pp0_iter13_reg = icmp_ln76_reg_131_pp0_iter12_reg.read();
        icmp_ln76_reg_131_pp0_iter14_reg = icmp_ln76_reg_131_pp0_iter13_reg.read();
        icmp_ln76_reg_131_pp0_iter15_reg = icmp_ln76_reg_131_pp0_iter14_reg.read();
        icmp_ln76_reg_131_pp0_iter16_reg = icmp_ln76_reg_131_pp0_iter15_reg.read();
        icmp_ln76_reg_131_pp0_iter17_reg = icmp_ln76_reg_131_pp0_iter16_reg.read();
        icmp_ln76_reg_131_pp0_iter18_reg = icmp_ln76_reg_131_pp0_iter17_reg.read();
        icmp_ln76_reg_131_pp0_iter19_reg = icmp_ln76_reg_131_pp0_iter18_reg.read();
        icmp_ln76_reg_131_pp0_iter20_reg = icmp_ln76_reg_131_pp0_iter19_reg.read();
        icmp_ln76_reg_131_pp0_iter21_reg = icmp_ln76_reg_131_pp0_iter20_reg.read();
        icmp_ln76_reg_131_pp0_iter22_reg = icmp_ln76_reg_131_pp0_iter21_reg.read();
        icmp_ln76_reg_131_pp0_iter23_reg = icmp_ln76_reg_131_pp0_iter22_reg.read();
        icmp_ln76_reg_131_pp0_iter24_reg = icmp_ln76_reg_131_pp0_iter23_reg.read();
        icmp_ln76_reg_131_pp0_iter25_reg = icmp_ln76_reg_131_pp0_iter24_reg.read();
        icmp_ln76_reg_131_pp0_iter26_reg = icmp_ln76_reg_131_pp0_iter25_reg.read();
        icmp_ln76_reg_131_pp0_iter27_reg = icmp_ln76_reg_131_pp0_iter26_reg.read();
        icmp_ln76_reg_131_pp0_iter28_reg = icmp_ln76_reg_131_pp0_iter27_reg.read();
        icmp_ln76_reg_131_pp0_iter29_reg = icmp_ln76_reg_131_pp0_iter28_reg.read();
        icmp_ln76_reg_131_pp0_iter2_reg = icmp_ln76_reg_131_pp0_iter1_reg.read();
        icmp_ln76_reg_131_pp0_iter30_reg = icmp_ln76_reg_131_pp0_iter29_reg.read();
        icmp_ln76_reg_131_pp0_iter31_reg = icmp_ln76_reg_131_pp0_iter30_reg.read();
        icmp_ln76_reg_131_pp0_iter32_reg = icmp_ln76_reg_131_pp0_iter31_reg.read();
        icmp_ln76_reg_131_pp0_iter33_reg = icmp_ln76_reg_131_pp0_iter32_reg.read();
        icmp_ln76_reg_131_pp0_iter34_reg = icmp_ln76_reg_131_pp0_iter33_reg.read();
        icmp_ln76_reg_131_pp0_iter35_reg = icmp_ln76_reg_131_pp0_iter34_reg.read();
        icmp_ln76_reg_131_pp0_iter36_reg = icmp_ln76_reg_131_pp0_iter35_reg.read();
        icmp_ln76_reg_131_pp0_iter37_reg = icmp_ln76_reg_131_pp0_iter36_reg.read();
        icmp_ln76_reg_131_pp0_iter38_reg = icmp_ln76_reg_131_pp0_iter37_reg.read();
        icmp_ln76_reg_131_pp0_iter39_reg = icmp_ln76_reg_131_pp0_iter38_reg.read();
        icmp_ln76_reg_131_pp0_iter3_reg = icmp_ln76_reg_131_pp0_iter2_reg.read();
        icmp_ln76_reg_131_pp0_iter40_reg = icmp_ln76_reg_131_pp0_iter39_reg.read();
        icmp_ln76_reg_131_pp0_iter41_reg = icmp_ln76_reg_131_pp0_iter40_reg.read();
        icmp_ln76_reg_131_pp0_iter42_reg = icmp_ln76_reg_131_pp0_iter41_reg.read();
        icmp_ln76_reg_131_pp0_iter43_reg = icmp_ln76_reg_131_pp0_iter42_reg.read();
        icmp_ln76_reg_131_pp0_iter44_reg = icmp_ln76_reg_131_pp0_iter43_reg.read();
        icmp_ln76_reg_131_pp0_iter45_reg = icmp_ln76_reg_131_pp0_iter44_reg.read();
        icmp_ln76_reg_131_pp0_iter46_reg = icmp_ln76_reg_131_pp0_iter45_reg.read();
        icmp_ln76_reg_131_pp0_iter47_reg = icmp_ln76_reg_131_pp0_iter46_reg.read();
        icmp_ln76_reg_131_pp0_iter48_reg = icmp_ln76_reg_131_pp0_iter47_reg.read();
        icmp_ln76_reg_131_pp0_iter49_reg = icmp_ln76_reg_131_pp0_iter48_reg.read();
        icmp_ln76_reg_131_pp0_iter4_reg = icmp_ln76_reg_131_pp0_iter3_reg.read();
        icmp_ln76_reg_131_pp0_iter50_reg = icmp_ln76_reg_131_pp0_iter49_reg.read();
        icmp_ln76_reg_131_pp0_iter51_reg = icmp_ln76_reg_131_pp0_iter50_reg.read();
        icmp_ln76_reg_131_pp0_iter52_reg = icmp_ln76_reg_131_pp0_iter51_reg.read();
        icmp_ln76_reg_131_pp0_iter53_reg = icmp_ln76_reg_131_pp0_iter52_reg.read();
        icmp_ln76_reg_131_pp0_iter54_reg = icmp_ln76_reg_131_pp0_iter53_reg.read();
        icmp_ln76_reg_131_pp0_iter55_reg = icmp_ln76_reg_131_pp0_iter54_reg.read();
        icmp_ln76_reg_131_pp0_iter56_reg = icmp_ln76_reg_131_pp0_iter55_reg.read();
        icmp_ln76_reg_131_pp0_iter57_reg = icmp_ln76_reg_131_pp0_iter56_reg.read();
        icmp_ln76_reg_131_pp0_iter5_reg = icmp_ln76_reg_131_pp0_iter4_reg.read();
        icmp_ln76_reg_131_pp0_iter6_reg = icmp_ln76_reg_131_pp0_iter5_reg.read();
        icmp_ln76_reg_131_pp0_iter7_reg = icmp_ln76_reg_131_pp0_iter6_reg.read();
        icmp_ln76_reg_131_pp0_iter8_reg = icmp_ln76_reg_131_pp0_iter7_reg.read();
        icmp_ln76_reg_131_pp0_iter9_reg = icmp_ln76_reg_131_pp0_iter8_reg.read();
        zext_ln79_reg_140_pp0_iter10_reg = zext_ln79_reg_140_pp0_iter9_reg.read();
        zext_ln79_reg_140_pp0_iter11_reg = zext_ln79_reg_140_pp0_iter10_reg.read();
        zext_ln79_reg_140_pp0_iter12_reg = zext_ln79_reg_140_pp0_iter11_reg.read();
        zext_ln79_reg_140_pp0_iter13_reg = zext_ln79_reg_140_pp0_iter12_reg.read();
        zext_ln79_reg_140_pp0_iter14_reg = zext_ln79_reg_140_pp0_iter13_reg.read();
        zext_ln79_reg_140_pp0_iter15_reg = zext_ln79_reg_140_pp0_iter14_reg.read();
        zext_ln79_reg_140_pp0_iter16_reg = zext_ln79_reg_140_pp0_iter15_reg.read();
        zext_ln79_reg_140_pp0_iter17_reg = zext_ln79_reg_140_pp0_iter16_reg.read();
        zext_ln79_reg_140_pp0_iter18_reg = zext_ln79_reg_140_pp0_iter17_reg.read();
        zext_ln79_reg_140_pp0_iter19_reg = zext_ln79_reg_140_pp0_iter18_reg.read();
        zext_ln79_reg_140_pp0_iter20_reg = zext_ln79_reg_140_pp0_iter19_reg.read();
        zext_ln79_reg_140_pp0_iter21_reg = zext_ln79_reg_140_pp0_iter20_reg.read();
        zext_ln79_reg_140_pp0_iter22_reg = zext_ln79_reg_140_pp0_iter21_reg.read();
        zext_ln79_reg_140_pp0_iter23_reg = zext_ln79_reg_140_pp0_iter22_reg.read();
        zext_ln79_reg_140_pp0_iter24_reg = zext_ln79_reg_140_pp0_iter23_reg.read();
        zext_ln79_reg_140_pp0_iter25_reg = zext_ln79_reg_140_pp0_iter24_reg.read();
        zext_ln79_reg_140_pp0_iter26_reg = zext_ln79_reg_140_pp0_iter25_reg.read();
        zext_ln79_reg_140_pp0_iter27_reg = zext_ln79_reg_140_pp0_iter26_reg.read();
        zext_ln79_reg_140_pp0_iter28_reg = zext_ln79_reg_140_pp0_iter27_reg.read();
        zext_ln79_reg_140_pp0_iter29_reg = zext_ln79_reg_140_pp0_iter28_reg.read();
        zext_ln79_reg_140_pp0_iter2_reg = zext_ln79_reg_140_pp0_iter1_reg.read();
        zext_ln79_reg_140_pp0_iter30_reg = zext_ln79_reg_140_pp0_iter29_reg.read();
        zext_ln79_reg_140_pp0_iter31_reg = zext_ln79_reg_140_pp0_iter30_reg.read();
        zext_ln79_reg_140_pp0_iter32_reg = zext_ln79_reg_140_pp0_iter31_reg.read();
        zext_ln79_reg_140_pp0_iter33_reg = zext_ln79_reg_140_pp0_iter32_reg.read();
        zext_ln79_reg_140_pp0_iter34_reg = zext_ln79_reg_140_pp0_iter33_reg.read();
        zext_ln79_reg_140_pp0_iter35_reg = zext_ln79_reg_140_pp0_iter34_reg.read();
        zext_ln79_reg_140_pp0_iter36_reg = zext_ln79_reg_140_pp0_iter35_reg.read();
        zext_ln79_reg_140_pp0_iter37_reg = zext_ln79_reg_140_pp0_iter36_reg.read();
        zext_ln79_reg_140_pp0_iter38_reg = zext_ln79_reg_140_pp0_iter37_reg.read();
        zext_ln79_reg_140_pp0_iter39_reg = zext_ln79_reg_140_pp0_iter38_reg.read();
        zext_ln79_reg_140_pp0_iter3_reg = zext_ln79_reg_140_pp0_iter2_reg.read();
        zext_ln79_reg_140_pp0_iter40_reg = zext_ln79_reg_140_pp0_iter39_reg.read();
        zext_ln79_reg_140_pp0_iter41_reg = zext_ln79_reg_140_pp0_iter40_reg.read();
        zext_ln79_reg_140_pp0_iter42_reg = zext_ln79_reg_140_pp0_iter41_reg.read();
        zext_ln79_reg_140_pp0_iter43_reg = zext_ln79_reg_140_pp0_iter42_reg.read();
        zext_ln79_reg_140_pp0_iter44_reg = zext_ln79_reg_140_pp0_iter43_reg.read();
        zext_ln79_reg_140_pp0_iter45_reg = zext_ln79_reg_140_pp0_iter44_reg.read();
        zext_ln79_reg_140_pp0_iter46_reg = zext_ln79_reg_140_pp0_iter45_reg.read();
        zext_ln79_reg_140_pp0_iter47_reg = zext_ln79_reg_140_pp0_iter46_reg.read();
        zext_ln79_reg_140_pp0_iter48_reg = zext_ln79_reg_140_pp0_iter47_reg.read();
        zext_ln79_reg_140_pp0_iter49_reg = zext_ln79_reg_140_pp0_iter48_reg.read();
        zext_ln79_reg_140_pp0_iter4_reg = zext_ln79_reg_140_pp0_iter3_reg.read();
        zext_ln79_reg_140_pp0_iter50_reg = zext_ln79_reg_140_pp0_iter49_reg.read();
        zext_ln79_reg_140_pp0_iter51_reg = zext_ln79_reg_140_pp0_iter50_reg.read();
        zext_ln79_reg_140_pp0_iter52_reg = zext_ln79_reg_140_pp0_iter51_reg.read();
        zext_ln79_reg_140_pp0_iter53_reg = zext_ln79_reg_140_pp0_iter52_reg.read();
        zext_ln79_reg_140_pp0_iter54_reg = zext_ln79_reg_140_pp0_iter53_reg.read();
        zext_ln79_reg_140_pp0_iter55_reg = zext_ln79_reg_140_pp0_iter54_reg.read();
        zext_ln79_reg_140_pp0_iter56_reg = zext_ln79_reg_140_pp0_iter55_reg.read();
        zext_ln79_reg_140_pp0_iter57_reg = zext_ln79_reg_140_pp0_iter56_reg.read();
        zext_ln79_reg_140_pp0_iter5_reg = zext_ln79_reg_140_pp0_iter4_reg.read();
        zext_ln79_reg_140_pp0_iter6_reg = zext_ln79_reg_140_pp0_iter5_reg.read();
        zext_ln79_reg_140_pp0_iter7_reg = zext_ln79_reg_140_pp0_iter6_reg.read();
        zext_ln79_reg_140_pp0_iter8_reg = zext_ln79_reg_140_pp0_iter7_reg.read();
        zext_ln79_reg_140_pp0_iter9_reg = zext_ln79_reg_140_pp0_iter8_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln76_reg_131_pp0_iter24_reg.read(), ap_const_lv1_0))) {
        tmp_1_reg_165 = grp_fu_84_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln76_reg_131_pp0_iter55_reg.read(), ap_const_lv1_0))) {
        tmp_2_reg_170 = grp_fu_89_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln76_reg_131_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        tmp_9_reg_155 = grp_fu_81_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln76_reg_131_pp0_iter19_reg.read(), ap_const_lv1_0))) {
        tmp_s_reg_160 = grp_fu_94_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln76_fu_99_p2.read(), ap_const_lv1_0))) {
        zext_ln79_reg_140 = zext_ln79_fu_111_p1.read();
    }
}

void sigmoid::thread_a_address0() {
    a_address0 =  (sc_lv<6>) (zext_ln79_fu_111_p1.read());
}

void sigmoid::thread_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void sigmoid::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void sigmoid::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void sigmoid::thread_ap_CS_fsm_state61() {
    ap_CS_fsm_state61 = ap_CS_fsm.read()[2];
}

void sigmoid::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state10_pp0_stage0_iter8() {
    ap_block_state10_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state11_pp0_stage0_iter9() {
    ap_block_state11_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state12_pp0_stage0_iter10() {
    ap_block_state12_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state13_pp0_stage0_iter11() {
    ap_block_state13_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state14_pp0_stage0_iter12() {
    ap_block_state14_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state15_pp0_stage0_iter13() {
    ap_block_state15_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state16_pp0_stage0_iter14() {
    ap_block_state16_pp0_stage0_iter14 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state17_pp0_stage0_iter15() {
    ap_block_state17_pp0_stage0_iter15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state18_pp0_stage0_iter16() {
    ap_block_state18_pp0_stage0_iter16 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state19_pp0_stage0_iter17() {
    ap_block_state19_pp0_stage0_iter17 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state20_pp0_stage0_iter18() {
    ap_block_state20_pp0_stage0_iter18 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state21_pp0_stage0_iter19() {
    ap_block_state21_pp0_stage0_iter19 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state22_pp0_stage0_iter20() {
    ap_block_state22_pp0_stage0_iter20 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state23_pp0_stage0_iter21() {
    ap_block_state23_pp0_stage0_iter21 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state24_pp0_stage0_iter22() {
    ap_block_state24_pp0_stage0_iter22 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state25_pp0_stage0_iter23() {
    ap_block_state25_pp0_stage0_iter23 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state26_pp0_stage0_iter24() {
    ap_block_state26_pp0_stage0_iter24 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state27_pp0_stage0_iter25() {
    ap_block_state27_pp0_stage0_iter25 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state28_pp0_stage0_iter26() {
    ap_block_state28_pp0_stage0_iter26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state29_pp0_stage0_iter27() {
    ap_block_state29_pp0_stage0_iter27 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state30_pp0_stage0_iter28() {
    ap_block_state30_pp0_stage0_iter28 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state31_pp0_stage0_iter29() {
    ap_block_state31_pp0_stage0_iter29 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state32_pp0_stage0_iter30() {
    ap_block_state32_pp0_stage0_iter30 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state33_pp0_stage0_iter31() {
    ap_block_state33_pp0_stage0_iter31 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state34_pp0_stage0_iter32() {
    ap_block_state34_pp0_stage0_iter32 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state35_pp0_stage0_iter33() {
    ap_block_state35_pp0_stage0_iter33 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state36_pp0_stage0_iter34() {
    ap_block_state36_pp0_stage0_iter34 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state37_pp0_stage0_iter35() {
    ap_block_state37_pp0_stage0_iter35 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state38_pp0_stage0_iter36() {
    ap_block_state38_pp0_stage0_iter36 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state39_pp0_stage0_iter37() {
    ap_block_state39_pp0_stage0_iter37 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state40_pp0_stage0_iter38() {
    ap_block_state40_pp0_stage0_iter38 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state41_pp0_stage0_iter39() {
    ap_block_state41_pp0_stage0_iter39 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state42_pp0_stage0_iter40() {
    ap_block_state42_pp0_stage0_iter40 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state43_pp0_stage0_iter41() {
    ap_block_state43_pp0_stage0_iter41 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state44_pp0_stage0_iter42() {
    ap_block_state44_pp0_stage0_iter42 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state45_pp0_stage0_iter43() {
    ap_block_state45_pp0_stage0_iter43 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state46_pp0_stage0_iter44() {
    ap_block_state46_pp0_stage0_iter44 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state47_pp0_stage0_iter45() {
    ap_block_state47_pp0_stage0_iter45 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state48_pp0_stage0_iter46() {
    ap_block_state48_pp0_stage0_iter46 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state49_pp0_stage0_iter47() {
    ap_block_state49_pp0_stage0_iter47 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state50_pp0_stage0_iter48() {
    ap_block_state50_pp0_stage0_iter48 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state51_pp0_stage0_iter49() {
    ap_block_state51_pp0_stage0_iter49 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state52_pp0_stage0_iter50() {
    ap_block_state52_pp0_stage0_iter50 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state53_pp0_stage0_iter51() {
    ap_block_state53_pp0_stage0_iter51 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state54_pp0_stage0_iter52() {
    ap_block_state54_pp0_stage0_iter52 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state55_pp0_stage0_iter53() {
    ap_block_state55_pp0_stage0_iter53 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state56_pp0_stage0_iter54() {
    ap_block_state56_pp0_stage0_iter54 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state57_pp0_stage0_iter55() {
    ap_block_state57_pp0_stage0_iter55 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state58_pp0_stage0_iter56() {
    ap_block_state58_pp0_stage0_iter56 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state59_pp0_stage0_iter57() {
    ap_block_state59_pp0_stage0_iter57 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state60_pp0_stage0_iter58() {
    ap_block_state60_pp0_stage0_iter58 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state7_pp0_stage0_iter5() {
    ap_block_state7_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state8_pp0_stage0_iter6() {
    ap_block_state8_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_block_state9_pp0_stage0_iter7() {
    ap_block_state9_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void sigmoid::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln76_fu_99_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void sigmoid::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state61.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sigmoid::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void sigmoid::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sigmoid::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter17.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter18.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter19.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter20.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter21.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter22.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter23.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter24.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter25.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter26.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter27.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter28.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter29.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter30.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter31.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter32.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter33.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter34.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter35.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter36.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter37.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter38.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter39.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter40.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter41.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter42.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter43.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter44.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter45.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter46.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter47.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter48.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter49.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter50.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter51.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter52.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter53.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter54.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter55.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter56.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter57.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter58.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void sigmoid::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state61.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sigmoid::thread_bitcast_ln79_fu_116_p1() {
    bitcast_ln79_fu_116_p1 = a_q0.read();
}

void sigmoid::thread_grp_fu_81_p0() {
    grp_fu_81_p0 = xor_ln79_fu_120_p2.read();
}

void sigmoid::thread_i_fu_105_p2() {
    i_fu_105_p2 = (!i_0_reg_66.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_0_reg_66.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void sigmoid::thread_icmp_ln76_fu_99_p2() {
    icmp_ln76_fu_99_p2 = (!i_0_reg_66.read().is_01() || !ap_const_lv7_40.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_66.read() == ap_const_lv7_40);
}

void sigmoid::thread_res_address0() {
    res_address0 =  (sc_lv<6>) (zext_ln79_reg_140_pp0_iter57_reg.read());
}

void sigmoid::thread_res_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter58.read()))) {
        res_ce0 = ap_const_logic_1;
    } else {
        res_ce0 = ap_const_logic_0;
    }
}

void sigmoid::thread_res_d0() {
    res_d0 = grp_fu_77_p1.read();
}

void sigmoid::thread_res_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter58.read()) && 
         esl_seteq<1,1,1>(icmp_ln76_reg_131_pp0_iter57_reg.read(), ap_const_lv1_0))) {
        res_we0 = ap_const_logic_1;
    } else {
        res_we0 = ap_const_logic_0;
    }
}

void sigmoid::thread_xor_ln79_fu_120_p2() {
    xor_ln79_fu_120_p2 = (bitcast_ln79_fu_116_p1.read() ^ ap_const_lv32_80000000);
}

void sigmoid::thread_zext_ln79_fu_111_p1() {
    zext_ln79_fu_111_p1 = esl_zext<64,7>(i_0_reg_66.read());
}

void sigmoid::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter58.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter57.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln76_fu_99_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter58.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter57.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln76_fu_99_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state61;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

